### ISSUE TITLE
More helpful errors

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/ruby-interpreter#12]
Missing a semi-colon is going to be one of the most common mistakes people make when writing MODL:

```
key1=value1
key2=value2
```
-> 

```
Parser Error: line1:0 no viable alternative at input 'key1'
```

What can we do to make this error more clear?

**Comment by elliottinvent** [comment]
I accidentally inserted a trailing `%` on a reference:

```
ref=123;
key=%ref%
```
->
```
stack level too deep
```

**Comment by twalmsley** [comment]
For the first error the Java interpreter reports:
```
org.antlr.v4.runtime.misc.ParseCancellationException: line 2:0 no viable alternative at input 'key1=value1key2'
```
which comes from the ANTLR4 Runtime. The Ruby version reports a shorter text string for some reason that I'll look into. I can try to make the error message the same for both runtimes, but any additional info required will have to be added by the interpreter and I don't yet know how difficult that will be.

The second error above is a coding bug.

**Comment by twalmsley** [comment]
For the second error, the Java interpreter gives this result, which looks incorrect:
```
[ {
  "ref" : 123
}, {
  "key" : "%ref%"
} ]
```
It should probably be:
```
[ {
  "ref" : 123
}, {
  "key" : "123%"
} ]
```

**Comment by twalmsley** [comment]
Fixed the `stack level too deep` error. It will be in v0.3.7

**Comment by twalmsley** [comment]
The Ruby error message is now the same as the Java error message for this MODL file - fixed in antlr4-ruby-runtime v0.2.6 which will be used by the next release of the Ruby interpreter (v0.3.7).

**Comment by twalmsley** [comment]
If the error message `line 2:0 no viable alternative at input 'key1=value1key2'` is not acceptable, please specify what you want to see, bearing in mind that it will affect all interpreters since we can't change all of the ANTLR4 runtimes.

**Comment by elliottinvent** [comment]
I think that's a lot more helpful since it shows the value and key joined which should highligh to authors that they need to split them.
