### ISSUE TITLE
Checking value of object reference in conditional

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/ruby-interpreter#19]
```
{
  !language?
     _language=en
};
test=%language
```
->
```
{
    "test": "en"
}
```
However, if the key that the `%language` value is assigned to is also called `language` then there is an error:
```
{
  !language?
     _language=en
};
language=%language
```
->
```
{
    "language": "%language"
}
```

Not a problem with java interpreter.

**Comment by twalmsley** [comment]
Tested with the latest version and it works fine. Just released to rubygems.org as v0.3.9

**Comment by twalmsley** [comment]
Was a bit too hasty - taking a 2nd look!

**Comment by twalmsley** [comment]
Published a fix to rubygems.org as v0.3.10.
