### ISSUE TITLE
Implement *expect

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/ruby-interpreter#3]
This instruction is currently ignored - I expect 0.5 to 1 day's effort to implement.

**Comment by alexdalitz** [comment]
I don’t think it needs to be implemented in the interpreter. All that needs to happen is for the instructions to be added to the class output to be used by the record generator. We will expose this as an endpoint until the JS interpreter can do the same.

**Comment by elliottinvent** [comment]
Originally, I was considering banning any key for a pair when `*expect` was defined but the pair didn't appear in `*expect`. So that's why Tony created this issue but have had a change of mind since then.

**Comment by twalmsley** [comment]
Ok, I'll add it to the `%*class` output and close the bug.

**Comment by twalmsley** [comment]
Added to gem v0.3.5
