### ISSUE TITLE
Inconsistent Parsing Behaviour

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/ruby-interpreter#5]
When I run the rake tests some test fail because structures like:
```
ab=ISO 8879\:1986;
```
parse as `nb_array`s instead of `STRING`s, but when I install the gem they parse correctly. I've checked that the ANTLR4 Ruby Runtime gem version doesn't change this behaviour so I'll need to dig into this at some point.

**Comment by elliottinvent** [comment]
Strange one. Obviously the `\` should escape the `:` in this example. Bizarre if the grammar is treating it as a string.

**Comment by twalmsley** [comment]
Bizarrely, this is not now causing a problem, but none of the changes look like they would cause this error. I'll monitor the situation for a while.

**Comment by twalmsley** [comment]
User error, the input should have been :
```
ab=ISO 8879\\:1986;
```

**Comment by elliottinvent** [comment]
A single `\` or `~` should be an escape.

**Comment by twalmsley** [comment]
When entering a `\` into a string in an input file it needs to be escaped as `\\`. I wasn't doing this in my test file.
